apiVersion: batch/v1
kind: Job
metadata:
  name: mysql
  namespace: people-nandy-io
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: api-people-nandy-io
        imagePullPolicy: Never
        command: ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "/opt/service/bin/db.py"]
        ports:
        - name: debug
          containerPort: 5678
          protocol: TCP