apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: people-nandy-io
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: docker.io/nandyio/people-api:0.1
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: db.mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: LOG_LEVEL
          value: WARNING
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        volumeMounts:
        - name: config
          mountPath: /opt/service/config
      volumes:
        - name: config
          configMap:
            name: config
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: people-nandy-io
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
